import OpenAI from 'openai';
import dotenv from 'dotenv';

dotenv.config({ path: '../../.env' });

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export interface AIAnalysisRequest {
  context: string;
  data: any;
  prompt: string;
}

export interface AIAnalysisResponse {
  analysis: string;
  riskScore: number;
  findings: string[];
  recommendations: string[];
}

export async function analyzeWithAI(request: AIAnalysisRequest): Promise<AIAnalysisResponse> {
  try {
    const systemPrompt = `You are an expert blockchain security analyst and DeFi risk assessor. 
Analyze the provided data and return a structured JSON response with:
- analysis: detailed analysis summary
- riskScore: numerical score from 0-100 (0=highest risk, 100=lowest risk)
- findings: array of key findings
- recommendations: array of recommendations

Be thorough, accurate, and conservative in your risk assessments.`;

    const userPrompt = `${request.context}\n\nData:\n${JSON.stringify(request.data, null, 2)}\n\n${request.prompt}`;

    const completion = await openai.chat.completions.create({
      model: process.env.OPENAI_MODEL || 'gpt-4-turbo-preview',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.3,
      response_format: { type: 'json_object' },
    });

    const response = completion.choices[0].message.content;
    if (!response) {
      throw new Error('No response from OpenAI');
    }

    const parsed = JSON.parse(response);
    
    return {
      analysis: parsed.analysis || 'No analysis provided',
      riskScore: Math.max(0, Math.min(100, parsed.riskScore || 50)),
      findings: parsed.findings || [],
      recommendations: parsed.recommendations || [],
    };
  } catch (error) {
    console.error('AI analysis error:', error);
    throw error;
  }
}

export async function generateReport(
  agentName: string,
  tokenAddress: string,
  analysis: AIAnalysisResponse
): Promise<string> {
  const report = `
# ${agentName} Verification Report

**Token Address:** ${tokenAddress}
**Timestamp:** ${new Date().toISOString()}
**Risk Score:** ${analysis.riskScore}/100

## Analysis Summary
${analysis.analysis}

## Key Findings
${analysis.findings.map((f, i) => `${i + 1}. ${f}`).join('\n')}

## Recommendations
${analysis.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

---
*This report was generated by an AI agent and should be used as part of a comprehensive due diligence process.*
`;

  return report;
}
